// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace data_test.Migrations
{
    [DbContext(typeof(DormitoryContext))]
    [Migration("20250710213844_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("data_test.Block", b =>
                {
                    b.Property<int>("BlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DormitoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BlockId");

                    b.HasIndex("DormitoryId");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("data_test.Dormitory", b =>
                {
                    b.Property<int>("DormitoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DormitoryId");

                    b.ToTable("Dormitories");
                });

            modelBuilder.Entity("data_test.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasDiscriminator<string>("PersonType").HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("data_test.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoomId");

                    b.HasIndex("BlockId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("data_test.Tool", b =>
                {
                    b.Property<int>("ToolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ToolId");

                    b.HasIndex("RoomId");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("data_test.Student", b =>
                {
                    b.HasBaseType("data_test.Person");

                    b.Property<int>("DormitoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("DormitoryId");

                    b.HasIndex("RoomId");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("data_test.SupervisorBlock", b =>
                {
                    b.HasBaseType("data_test.Person");

                    b.Property<int>("BlockId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("BlockId");

                    b.HasDiscriminator().HasValue("SupervisorBlock");
                });

            modelBuilder.Entity("data_test.SupervisorDormitory", b =>
                {
                    b.HasBaseType("data_test.Person");

                    b.Property<int>("DormitoryId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("DormitoryId");

                    b.ToTable("Person", t =>
                        {
                            t.Property("DormitoryId")
                                .HasColumnName("SupervisorDormitory_DormitoryId");
                        });

                    b.HasDiscriminator().HasValue("SupervisorDormitory");
                });

            modelBuilder.Entity("data_test.Block", b =>
                {
                    b.HasOne("data_test.Dormitory", "Dormitory")
                        .WithMany("Blocks")
                        .HasForeignKey("DormitoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dormitory");
                });

            modelBuilder.Entity("data_test.Room", b =>
                {
                    b.HasOne("data_test.Block", "Block")
                        .WithMany("Rooms")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");
                });

            modelBuilder.Entity("data_test.Tool", b =>
                {
                    b.HasOne("data_test.Room", "Room")
                        .WithMany("Tools")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("data_test.Student", b =>
                {
                    b.HasOne("data_test.Dormitory", "Dormitory")
                        .WithMany("Students")
                        .HasForeignKey("DormitoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("data_test.Room", "Room")
                        .WithMany("Students")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dormitory");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("data_test.SupervisorBlock", b =>
                {
                    b.HasOne("data_test.Block", "Block")
                        .WithMany("Supervisors")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");
                });

            modelBuilder.Entity("data_test.SupervisorDormitory", b =>
                {
                    b.HasOne("data_test.Dormitory", "Dormitory")
                        .WithMany("Supervisors")
                        .HasForeignKey("DormitoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dormitory");
                });

            modelBuilder.Entity("data_test.Block", b =>
                {
                    b.Navigation("Rooms");

                    b.Navigation("Supervisors");
                });

            modelBuilder.Entity("data_test.Dormitory", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Students");

                    b.Navigation("Supervisors");
                });

            modelBuilder.Entity("data_test.Room", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Tools");
                });
#pragma warning restore 612, 618
        }
    }
}
